### ISSUE TITLE
Anpassung Budgetscript 

### ISSUE THREAD

**Issue by Holger-GZ** [GermanZero-de/localzero-generator-core#406] opened 2024-09-23 07:44 UTC
Anpassung Budgetscript muss @Ultramarin95  nur nochmal testen (und alten Branch https://github.com/GermanZero-de/localzero-generator-core/tree/refactor-budget löschen)

**Comment by Jeniffere** [comment] 2024-10-07 19:22
Is duplicate of https://github.com/GermanZero-de/localzero-generator-core/issues/410

**Closed by Jeniffere** 2024-10-07 19:22 UTC
